#include "AppResourceId.h"

const wchar_t* IDC_EDITDATE = L"IDC_EDITDATE";
const wchar_t* IDC_EDITDATE_DISABLE = L"IDC_EDITDATE_DISABLE";
const wchar_t* IDC_EDITDATE_NO_TITLE = L"IDC_EDITDATE_NO_TITLE";
const wchar_t* IDC_EDITTIME = L"IDC_EDITTIME";
const wchar_t* IDC_SCROLLPANEL = L"IDC_SCROLLPANEL";
const wchar_t* IDC_SPLITPANEL = L"IDC_SPLITPANEL";
const wchar_t* IDC_WEB1 = L"IDC_WEB1";
const wchar_t* IDF_FORM = L"IDF_FORM";
const wchar_t* IDF_MY_HONDANA_DETAIL_FORM = L"IDF_MY_HONDANA_DETAIL_FORM";
const wchar_t* IDF_MY_HONDANA_MAIN_FORM = L"IDF_MY_HONDANA_MAIN_FORM";
const wchar_t* IDF_MY_HONDANA_MARKET_FORM = L"IDF_MY_HONDANA_MARKET_FORM";
const wchar_t* ID_SCNT_MAINSCENE = L"ID_SCNT_MAINSCENE";
const wchar_t* IDC_BUTTON_OK = L"IDC_BUTTON_OK";
